Update docker-publish.yml

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -12,19 +12,14 @@ permissions: write-all
 
 jobs:
   build:
-    runs-on: windows-latest
-
+    runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Add files to git
-        run: |
-          echo "a" >> test
-          git config user.name "$env:GITHUB_ACTOR"
-          git config user.email "$env:GITHUB_ACTOR@users.noreply.github.com"
-          git status
-          git add .
-          git commit -m "chore: Update Game Resources"
-          echo "$env:GITHUB_RUN_ID"
-          gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/moomiji/-/actions/runs/4973052759
-        env:
-          GH_TOKEN: ${{ github.token }}
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Run a command that might fail
+        run: exit 1
+        continue-on-error: true
+
+      - name: This step will still run
+        run: echo "This step runs even if the previous step fails."
